### ISSUE TITLE
F003-mevalonate, F003-mevalonate-V002: need several fixes (as described)

### ISSUE THREAD

**Issue by ibalaur** [metabolismregulation/metabolismregulation.github.io#10]
Several corrections are needed:
- Ca++ is drawn in yEd as a "state variable", but should be replaced by "simple chemical";
- the "inactive" state variable of the CaMKKß is drawn as a state variable of the edge/arc, but should be added to the CaMKKß macromolecule.
Please test using http://metabolismregulation.org/mevalonate/.

**Comment by ibalaur** [comment]
The arc from CaMKKß (with inactive state variable) to be checked/re-drawn also.

**Comment by amazein** [comment]
The three errors are corrected for those files, updated in /downloads.
