### ISSUE TITLE
Units of information for glucose should be attached to the glyph

### ISSUE THREAD

**Issue by ibalaur** [metabolismregulation/metabolismregulation.github.io#11]
In the Glycogen diagram (files: F004-glycogen-liver-V001, F004-glycogen-muscle-V003, F004-glycogen-muscle, F004-glycogen-muscle-V004), the units of information glycogen and N:n for glucose (center for the diagram) are attached to the arcs. These should be attached to the glyph.

**Comment by amazein** [comment]
Hi Irina, Thank you for looking closely into details for each diagram. For your consideration: maybe for errors like that it is worth to display some kind of validation message after conversion? This type might reappear and it is specific for yEd - kind of too easy to attach to a link by mistake. Potentially, I can imagine, could be autocorrected.

**Comment by amazein** [comment]
The files are corrected and uploaded to the /downloads folder on GitHub
