### ISSUE TITLE
F012-cAMP: State variable to be attached to glyph

### ISSUE THREAD

**Issue by ibalaur** [metabolismregulation/metabolismregulation.github.io#12]
In F012-cAMP, the state variable "active" for PI3K must be corrected (top, left of the diagram).

**Comment by amazein** [comment]
The graphml is corrected and replaced in /downloads

**Comment by amazein** [comment]
Should I close issues in such cases or keep it so you would close when sbgnml is generated?

**Comment by ibalaur** [comment]
Test OK.
