### ISSUE TITLE
F008-enos: cardinality of the arc needs correction

### ISSUE THREAD

**Issue by ibalaur** [metabolismregulation/metabolismregulation.github.io#13]
Cardinality of the arc should be given as the arc's label; however, for processes involving NADPH and O2 (bottom, right), this is introduced as additional shapes - which are not recognised during translation to SBGN.
Please see yEd files: F008-enos_v009, F008-enos_v011, F008-enos.

**Comment by amazein** [comment]
This is strange, I remember doing those and in yEd it looks fine for the bottom-right NADPH and O2: cardinality as a level of the arc. I have redone the labels, please see if it works now (updated in /downloads for the 3 files).

**Comment by ibalaur** [comment]
Files are translated OK.
Perhaps, the converter should be extended to accept additional shapes as arcs' cardinality. However, if this extension is considered, the convertion may take more time for checking all additional shapes that are found at a resonable distance of a specific arc in order to be considered as cardinality information; an immediate issue that may arise is that the distance may differ among diagrams, and the cardinality to be assigned wrongly to arcs (smaller distance between the shape and arcs that do not have that cardinality) or not to be assigned (higher distance between the shape and the specific arc that must have the given cardinality). Providing cardinality information as edge's label is the best and safest way to proceed.

**Comment by amazein** [comment]
Hi Irina, I am not sure this is a conversion problem. Have you checked the updated files, did it work with them? If it worked, then probably the previous version of yEd handled it differently or I did something differently. To make cardinality appear this way, quite a few things in properties needed to be changed (see under Cardinality hare http://metabolismregulation.org/help/), maybe after that something went wrong.
