### ISSUE TITLE
"Self" arc to be removed from initial F003-mevalonate diagrams (yEd GraphML format) 

### ISSUE THREAD

**Issue by ibalaur** [metabolismregulation/metabolismregulation.github.io#3]
There is an extra "self" arc for the complex formation process involving the AMPKα, AMPKβ and AMPKγ. It has to be removed as this is not SBGN compliant.
Input files: F003-mevalonate-V002.graphml and F003-mevalonate.graphml
<img width="479" alt="Mevalonate_issue" src="https://user-images.githubusercontent.com/16227615/55630682-8e070580-57b6-11e9-91a3-b2cbaa8025ce.png">

**Comment by amazein** [comment]
The graphml files have been updated, uploaded to downloads folder
