### ISSUE TITLE
F008-enos: process to be corrected

### ISSUE THREAD

**Issue by ibalaur** [metabolismregulation/metabolismregulation.github.io#5]
The process involving NADPH must have at least one ongoing arc. 
Input files: F008-enos.graphml and F008-enos_v011. graphml.

<img width="315" alt="InputF008-enos" src="https://user-images.githubusercontent.com/16227615/55633257-39668900-57bc-11e9-94f5-dc5b2c70f03e.png">

**Comment by amazein** [comment]
Corrected and replaced in /downloads folder
